project:
  type: website
  output-dir: docs

website:
  title: "Ethnographies des mondes ruraux"
  site-url: "https://ethnographies-des-mondes-ruraux.github.io/"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



